services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: upgrade-palm-tree/app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DB_HOST=db
  db:
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPw
      - POSTGRES_DB=dbName

